GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/63e6876d7dcb98c49042f9ee

###

GET http://localhost:3001/api/persons/63e68

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tupu Ankka",
    "number": "555-313 3134"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "555-313 3134"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tupu Ankka"
}

###


POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lauri Lauseke",
    "number": "09-1234556"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Sanni Säännöllinen",
    "number": "040-22334455"
}


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Vilperi Vääräleuka",
    "number": "+358-1234556"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tiku Orava",
    "number": "555-12345677"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Väärä Numero",
    "number": "1234"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lo",
    "number": "123-456789900"
}

###

PUT http://localhost:3001/api/persons/63e78ebc17bcc3265bb0c0b9
Content-Type: application/json

{
    "name": "Taku Orava",
    "number": "555-12345677"
}

###

DELETE http://localhost:3001/api/persons/63e7b144183bd36d7f70a6f6