GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/63e6876d7dcb98c49042f9ee

###

GET http://localhost:3001/api/persons/63e68

###

GET http://localhost:3001/info

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tupu Ankka",
    "number": "555-313 3134"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "555-313 3134"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tupu Ankka"
}

###


POST http://localhost:3001/api/persons
Content-Type: application/json

{}

###

PUT http://localhost:3001/api/persons/63e746c9e4530570814cc4b1
Content-Type: application/json

{
    "name": "Aku Ankka",
    "number": "555-313 3133"
}

###

DELETE http://localhost:3001/api/persons/63e7852f554392bf4ce64131